nginx:
  build: docker
  ports:
    - "81:80"
  links:
    - php
    - redis
    - db
  volumes:
    - ./:/app

php:
  build: php-fpm
  volumes:
    - ./:/app
  working_dir: /app
  links:
    - redis
    - db

redis:
    image: redis
    restart: unless-stopped
    ports:
        - "6379:6379"

db:
    image: mysql
    ports:
      - "3307:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: restapp