# Application container
php:
    build: .
    restart: unless-stopped
    volumes:
        - ./:/server/http
    ports:
        - "81:80"
        - "443:443"
    links:
        - db
        - redis
    environment:
        DEBUG: 'true'

redis:
    image: redis
    restart: unless-stopped
    ports:
        - "6379:6379"

db:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: restapp
