Rest\CategoryBundle\Entity\Category:
    properties:
        name:
            - NotBlank:
                message: The name can not be blank
        slug:
            - NotBlank:
                message: The slug can not be blank